CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilations (
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(50) NOT NULL,
    pinned boolean
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(250) NOT NULL,
    email varchar(254) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat float NOT NULL,
    lon float NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(120) NOT NULL,
    annotation varchar(2000) NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(category_id) ON DELETE CASCADE,
    description varchar(7000) NOT NULL,
    initiator_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_on TIMESTAMP WITHOUT TIME ZONE,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    event_date TIMESTAMP WITHOUT TIME ZONE,
    location_id BIGINT NOT NULL REFERENCES locations(location_id) ON DELETE CASCADE,
    participant_limit int DEFAULT 0,
    request_moderation boolean DEFAULT TRUE,
    confirmed_requests int DEFAULT 0,
    paid boolean DEFAULT FALSE,
    state varchar(20) NOT NULL,
    views BIGINT DEFAULT 0,
    rating DECIMAL(2, 1) DEFAULT 0.0
);

CREATE TABLE IF NOT EXISTS event_compilation (
    event_id BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    compilation_id BIGINT NOT NULL REFERENCES compilations(compilation_id) ON DELETE CASCADE,
    PRIMARY KEY (event_id, compilation_id)
);

CREATE TABLE IF NOT EXISTS requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    requester_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    status varchar(20) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(2000) NOT NULL,
    author_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE,
    rating int NOT NULL
);

CREATE TABLE IF NOT EXISTS comment_photos (
    photo_id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    comment_id BIGINT NOT NULL REFERENCES comments(comment_id) ON DELETE CASCADE,
    name varchar(255),
    type varchar(50),
    data BYTEA
);